/**
 *
 * $Id$
 */
package system.validation;

import org.eclipse.emf.common.util.EList;

import system.Element;
import system.Entity;
import system.MethodType;

/**
 * A sample validator interface for {@link system.Form}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FormValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateMethod(MethodType value);
	boolean validateElements(EList<Element> value);
	boolean validateEntity(Entity value);
}
