/**
 *
 * $Id$
 */
package system.validation;

import system.DataType;

/**
 * A sample validator interface for {@link system.Static_Content}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Static_ContentValidator {
	boolean validate();

	boolean validateType(DataType value);
}
