/**
 *
 * $Id$
 */
package A3.validation;

import A3.D_Content;
import A3.Page;
import A3.Static_Content;

import java.math.BigInteger;

/**
 * A sample validator interface for {@link A3.Page}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PageValidator {
	boolean validate();

	boolean validateIdentifier(BigInteger value);
	boolean validateUrl(String value);
	boolean validateTitle(String value);
	boolean validateD_content(D_Content value);
	boolean validateS_content(Static_Content value);
	boolean validatePages(Page value);
	boolean validateCountry(String value);
}
