
-- System sys 
-- Autogenerated V2.4

DROP TABLE elements;
DROP TABLE forms;
DROP TABLE dynamic_content;
DROP TABLE attributes;
DROP TABLE entities;
DROP TABLE static_content;
DROP TABLE pages;
DROP TABLE system;


CREATE TABLE system (
	id SERIAL PRIMARY KEY, 
	name varchar(255),
	description varchar(255),
	version int,
	sub_version int
);

CREATE TABLE pages (
	id SERIAL PRIMARY KEY, 
	title varchar(255),
	url varchar(255),
	description varchar(255),
	is_home_page varchar(255),
    system_id INT REFERENCES system(id)
);

CREATE TABLE static_content (
	id SERIAL PRIMARY KEY, 
	type varchar(255),
	text varchar(255),
	page_id INT REFERENCES pages(id)
);


CREATE TABLE entities (
	id SERIAL PRIMARY KEY, 
	name varchar(255),
	description varchar(255),
    system_id INT REFERENCES system(id)
);

CREATE TABLE attributes (
	id SERIAL PRIMARY KEY, 
	name varchar(255),
	description varchar(255),
	type varchar(255),
	is_primary_key varchar(255),
	entity_id INT REFERENCES entities(id)
);

CREATE TABLE dynamic_content (
	id SERIAL PRIMARY KEY, 
	attribute_id INT REFERENCES attributes(id),
	entity_id INT REFERENCES entities(id),
	page_id INT REFERENCES pages(id)
);

CREATE TABLE forms (
	id SERIAL PRIMARY KEY,
	name varchar(255),
	description varchar(255),
	method varchar(255),
	entity_id INT REFERENCES entities(id),
	page_id INT REFERENCES pages(id)
);

CREATE TABLE elements (
	id SERIAL PRIMARY KEY,
	name varchar(255),
	description varchar(255),
	label varchar(255),
	attribute_id INT REFERENCES attributes(id),
	form_id INT REFERENCES forms(id)
);


INSERT INTO system (ID, name, description, version, sub_version) VALUES (1, 'sys', 'Here is our system', 2, 4);
	
INSERT INTO entities (ID, name, description, system_id) VALUES (1,'User', 'A user within the system', 1);
INSERT INTO attributes (ID, name, description, type, is_primary_key, entity_id) VALUES (1,'ID','The user identifier', 'int', 'true', 1); 
INSERT INTO attributes (ID, name, description, type, is_primary_key, entity_id) VALUES (2,'Username','The users username', 'text', 'false', 1); 
	
	
INSERT INTO pages (ID, title, url, description, is_home_page, system_id) VALUES (1, 'Home', 'website.com', 'The home page', 'true', 1);
INSERT INTO static_content (ID, type, text, page_id) VALUES (1,'h1', 'Welcome to the homepage', 1);
INSERT INTO forms (ID, name, description, method, entity_id, page_id) VALUES (1, 'Sign up', '', 'post','1', 1);
INSERT INTO elements (ID, name, description, label, attribute_id, form_id) VALUES (1, 'username', 'Username', 'Enter your username', '2', '1');
	
	
INSERT INTO pages (ID, title, url, description, is_home_page, system_id) VALUES (2, 'Profile', 'website.com/profile', 'The profile page', 'false', 1);
INSERT INTO static_content (ID, type, text, page_id) VALUES (2,'h2', 'Profile page', 2);
INSERT INTO dynamic_content (ID, attribute_id, entity_id, page_id) VALUES (1, 2, 1, 2);
	

SELECT (title, description, url) FROM pages WHERE is_home_page = 'true';

SELECT * FROM attributes WHERE entity_id = 1 AND is_primary_key = 'true';



