/**
 *
 * $Id$
 */
package tutorial.validation;

import java.math.BigInteger;

import org.eclipse.emf.common.util.EList;

import tutorial.Library;
import tutorial.Loan;

/**
 * A sample validator interface for {@link tutorial.Book}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BookValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateCopies(BigInteger value);
	boolean validateLibrary(Library value);
	boolean validateLoans(EList<Loan> value);
}
