/**
 *
 * $Id$
 */
package tutorial.validation;

import java.util.Date;

import tutorial.Book;
import tutorial.Member;

/**
 * A sample validator interface for {@link tutorial.Loan}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LoanValidator {
	boolean validate();

	boolean validateBook(Book value);
	boolean validateMember(Member value);
	boolean validateDate(Date value);
}
