/**
 *
 * $Id$
 */
package tutorial.validation;

import org.eclipse.emf.common.util.EList;

import tutorial.Book;
import tutorial.Loan;
import tutorial.Member;

/**
 * A sample validator interface for {@link tutorial.Library}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LibraryValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateBooks(EList<Book> value);
	boolean validateLoans(EList<Loan> value);
	boolean validateMembers(EList<Member> value);
}
