/**
 *
 * $Id$
 */
package system.validation;

import java.math.BigInteger;

import org.eclipse.emf.common.util.EList;

import system.D_Individual;

/**
 * A sample validator interface for {@link system.D_Index}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface D_IndexValidator {
	boolean validate();

	boolean validateIndividual(EList<D_Individual> value);
	boolean validateIndex_identifier(BigInteger value);
}
