/**
 *
 * $Id$
 */
package system.validation;

import java.math.BigInteger;
import org.eclipse.emf.common.util.EList;

import system.Entity;
import system.Page;

/**
 * A sample validator interface for {@link system.System}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SystemValidator {
	boolean validate();

	boolean validateVersion(BigInteger value);

	boolean validateSubversion(BigInteger value);

	boolean validateEntities(EList<Entity> value);
	boolean validatePages(EList<Page> value);
}
